version: '3.8'

services:
  spring-app1:
    build:
      context: ../testforjenkings
    ports:
      - "8081:8080"
  spring-app2:
    build:
      context: ../testforjenkings
    ports:
      - "8082:8080"

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - spring-app1
      - spring-app2