- name: Install Maven
  hosts: all
  become: yes
  tasks:
    - name: Install Maven
      apt:
        name: maven
        state: present

- name: Deploy Java Application
  hosts: all
  become: yes
  tasks:
    - name: Clone a GitHub repository
      git:
        repo: https://github.com/saeed-salami/jenkins.git
        dest: /mnt/d/forAnyTest
        clone: yes 
        update: yes

    - name: Build the application with Maven
      command: mvn clean install
      args:
        chdir: /mnt/d/forAnyTest/

    - name: Copy your-app.jar to destination
      copy:
        src: /mnt/d/forAnyTest/target/testforjenkings-0.0.1-SNAPSHOT.jar
        dest: /mnt/d/forAnyTest/
        remote_src: yes
    - name: Run Java application
      command: java -jar /mnt/d/forAnyTest/testforjenkings-0.0.1-SNAPSHOT.jar
      register: java_run
      failed_when: java_run.rc not in [0, 1]  